name: Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  docs:
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build docs
        run: |
          cargo doc
          echo "<meta http-equiv=\"refresh\" content=\"0; url=tauri_nspanel\">" > target/doc/index.html
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/doc
