name: Format

on:
  push:
    branches:
      - v2
      - v1
  pull_request:
    branches:
      - v2
      - v1

jobs:
  format:
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Install rustfmt with stable toolchain
      uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --manifest-path=Cargo.toml --all -- --check
