name: Clippy
on:
  push:
    branches:
      - v2
      - v1
  pull_request:
    branches:
      - v2
      - v1
jobs:
  clippy:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Install clippy with stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --manifest-path=Cargo.toml --all-targets --all-features -- -D warnings
          name: clippy
